#!/bin/bash
git clone https://github.com/hashicorp/consul-k8s-l7-obs-guide.git guide
sed -i 's/default: true/default: false/g' guide/consul-values.yaml

git clone https://github.com/hashicorp/consul-helm.git

cat <<EOF | /usr/local/bin/kubectl apply -f -
---
apiVersion: v1
kind: Service
metadata:
  name: consul-service
spec:
  type: NodePort
  selector:
    app: consul
    component: server
  ports:
  - name: http
    protocol: TCP
    port: 8500
    targetPort: 8500
    nodePort: 30085
EOF

cat <<EOF | /usr/local/bin/kubectl apply -f -
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30030
EOF
